import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class UI {


    public boolean muteon = true;
    public int temp1, temp2;
    public BoardLogic boardLogic;
    public Main main;

    public UI() {
        musicSlider.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                System.out.println(musicSlider.getValue());
                boardLogic.sounds.setMusicvolume(musicSlider.getValue());
            }
        });
        muteButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("Mute!");
                if (muteon) {
                    System.out.println("unmute");
                    muteButton.setText("Unmute All");
                    temp1 = sfxSlider.getValue();
                    temp2 = musicSlider.getValue();
                    boardLogic.sounds.setMusicvolume(0);
                    boardLogic.sounds.setSfxvolume(0);
                    sfxSlider.setValue(0);
                    musicSlider.setValue(0);
                    muteon = !muteon;
                } else {
                    sfxSlider.setValue(temp1);
                    musicSlider.setValue(temp2);
                    boardLogic.sounds.setMusicvolume(temp2);
                    boardLogic.sounds.setSfxvolume(temp1);
                    System.out.println("mute now");
                    muteButton.setText("Mute All");
                    muteon = !muteon;
                }
            }
        });
        newGameButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                Object[] options = {"Yes, please",
                        "No, thanks"};
                int n = JOptionPane.showOptionDialog(JOptionPane.getRootFrame(),
                        "Want to create a new game?",
                        "A Silly Question",
                        JOptionPane.YES_NO_CANCEL_OPTION,
                        JOptionPane.QUESTION_MESSAGE,
                        null,
                        options,
                        options[1]);

                System.out.println("New game! " + n);

                if (n == 0) {
                    boardLogic.newGame();
                }
                /*String spm = "Want to create a new game?";
                String svar = JOptionPane.showInputDialog(spm, "ja");*/

            }
        });
        sfxSlider.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                System.out.println(sfxSlider.getValue());
                boardLogic.sounds.setSfxvolume(sfxSlider.getValue());
            }
        });
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("UI");
        frame.setContentPane(new UI().UI_Panel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    private JButton playButton;
    private JButton stopButton;
    private JSlider musicSlider;
    private JButton muteButton;
    private JPanel UI_Panel;
    private JButton newGameButton;
    private JSlider sfxSlider;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        UI_Panel = new JPanel();
        UI_Panel.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("Sound Options");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        UI_Panel.add(label1, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        UI_Panel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 9;
        gbc.fill = GridBagConstraints.VERTICAL;
        UI_Panel.add(spacer2, gbc);
        musicSlider = new JSlider();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        UI_Panel.add(musicSlider, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Music Volume");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        UI_Panel.add(label2, gbc);
        muteButton = new JButton();
        muteButton.setText("Mute All");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        UI_Panel.add(muteButton, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.VERTICAL;
        UI_Panel.add(spacer3, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Game Options");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        UI_Panel.add(label3, gbc);
        newGameButton = new JButton();
        newGameButton.setText("New Game");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        UI_Panel.add(newGameButton, gbc);
        sfxSlider = new JSlider();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        UI_Panel.add(sfxSlider, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("SFX Volume");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        UI_Panel.add(label4, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return UI_Panel;
    }

}
